export const USER_LOGGED = 'session.USER_LOGGED';
export const USER_LOGGED_FAILED = 'session.USER_LOGGED_FAILED';
export const USER_LOGGED_SUCCESFULLY = 'session.USER_LOGGED_SUCCESFULLY';
export const SESSION_USERNAME_CHANGED = 'session.SESSION_USERNAME_CHANGED';
export const SESSION_PASSWORD_CHANGED = 'session.SESSION_PASSWORD_CHANGED';
export const SESSION_CLOSED = 'session.SESSION_CLOSED';
